### ISSUE TITLE
Add user emulation source code to repository

### ISSUE THREAD

**Issue by ru37z** [fkie-cad/socbed#15]
**Is your feature request related to a problem? Please describe.**

The user emulation agent is currently only included as a (compressed) Python Executable (PEX) file, which is uploaded to the Client VM during the provisioning process. This makes it difficult to view and change its source code.

**Describe the solution you'd like**

The user emulation source code files (*.py) should be included in the repository and automatically compiled to a PEX file during the provisioning process.

**Describe alternatives you've considered**

As an alternative, it might also be possible to upload the code directly to the Client, without using a PEX file. In this case, all dependencies must be installed on the Client, probably via pip. The advantage would be that the user emulation code can be viewed and edited directly on the client.

**Additional context**

AFAIK, the Python version (major and minor) on the system where the PEX file is compiled (i.e., the build server) must be the same as on the target system (i.e., the client). It might therefore be necessary to change the Python version of the Client, in case there is no other solution.

**Comment by Cyb3r-Monk** [comment]
Is there a planned date for this? It would be great to have the source code for customizations

**Comment by ru37z** [comment]
We'll try to get this done within the next two weeks.

**Comment by LouisHacklaender** [comment]
Hello Cyb3r-Monk, we are currently working on the automatic compiling process of the userbehavior.pex file.
The source code of the userbehavior can already be found in the [integrate-userbehavior](https://github.com/fkie-cad/socbed/tree/integrate-userbehavior/src/userbehavior) branch.

**Comment by Cyb3r-Monk** [comment]
Hi Louis, is it going to be possible to use it separately on different environments?

**Comment by LouisHacklaender** [comment]
AFAIK, currently the emulated userbehavior mainly works in SOCBED. Since some configurations are specific to the SOCBED environment, I do not think it can be used in different environments as it is - but on the other hand, I guess that it can be used with some changes, e.g. in the `src/userbehavior/userbehavior/breachsetup.py`. 

Unfortunately, I am no expert when it comes to the emulated userbehavior and I am not of much help when it comes to adapting it.

**Comment by LouisHacklaender** [comment]
Update on the issue: 

PEX ["has never officially supported Windows, though it appears that older versions worked to some degree"](https://github.com/jjjake/internetarchive/issues/414#issuecomment-860977117). Compiling a PEX file for the Windows client worked with `pex==1.6.2.` ([info](https://github.com/pantsbuild/pex/issues/1155#issuecomment-752709281)) but since some dependencies have been updated a newer PEX version is required. Compiling the PEX file for Windows with newer versions is not possible at the moment.

Because of this, the alternative described in this issue will be implemented.

**Comment by ru37z** [comment]
The alternative solution has been merged into the dev branch and will be merged into main if all tests run successfully.

**Comment by ru37z** [comment]
After fixing a few bugs in `dev`, the solution finally made it into `main`. :beers:
